apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: chuotcona123/user-service:1.0.0
          ports:
            - containerPort: 3001
          env:
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: service-config
                  key: mongo-url
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  type: NodePort
  selector:
    app: user
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30102
